<%@ Page Title="Role Master" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="RoleMaster.aspx.cs" Inherits="UlaWebAgsWF.RoleMaster" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <script type="text/javascript">
        $(document).ready(function () {
            $('#<%= CerateNewRoleLink.ClientID %>').click(function (e) {
                e.preventDefault();
                $('#<%= CreateNewRoleContainer.ClientID %>').toggle("slow", "swing");
            });
        });
    </script>
    <div class="container">
        <div class="page-header">
            <h2>
                Roles
            </h2>
        </div>
        <asp:Panel ID="SuccessMsg" runat="server" Visible="false" CssClass="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <asp:Label ID="SuccessMsgText" runat="server" Text="" />
        </asp:Panel>
        <asp:Panel ID="FailureMsg" runat="server" Visible="false" CssClass="alert alert-danger alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <asp:Label ID="FailureMsgText" runat="server" Text="" />
        </asp:Panel>
        <asp:Panel ID="CreateNewRoleLinkContainer" CssClass="text-left" runat="server">
            <asp:LinkButton ID="CerateNewRoleLink" style="padding: 0px;" CssClass="btn btn-link" Text="Create Role" runat="server" />
        </asp:Panel>
        <asp:Panel ID="CreateNewRoleContainer" runat="server" style="display:none">
            <form class="form-inline">
                <div class="form-group">
                    <label for="NewRoleName">Role Name:</label>
                    <asp:TextBox ID="NewRoleName" runat="server" CssClass="form-control" />
                    <asp:RequiredFieldValidator ID="RequiredFieldNewRoleName" ControlToValidate="NewRoleName" CssClass="text text-danger" runat="server" ErrorMessage="Please enter Role Name" Display="Dynamic"></asp:RequiredFieldValidator>
                </div>
                <div class="form-group">
                    <label for="ScreenAuthorizedFor">Select Screens:</label>
                    <asp:CheckBoxList ID="ScreenAuthorizedFor" CssClass="form-control"  runat="server">
                    </asp:CheckBoxList>
                </div>
                <div class="checkbox">
                    <asp:CheckBox ID="CbxIsSU" runat="server" Text="Super User?" />
                </div>
                <asp:Button ID="NewRoleBtnSubmit" UseSubmitBehavior="false" runat="server" CssClass="btn btn-default" Text="Add Role" OnClick="NewRoleBtnSubmit_Click" />
            </form>
        </asp:Panel>
        <br clear="all" />
        <asp:GridView ID="RolesDGV" AutoGenerateColumns="false" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" OnRowEditing="RolesDGV_RowEditing" OnRowUpdating="RolesDGV_RowUpdating" OnRowUpdated="RolesDGV_RowUpdated" OnRowDeleting="RolesDGV_RowDeleting" OnRowCancelingEdit="RolesDGV_RowCancelingEdit" OnRowDeleted="RolesDGV_RowDeleted" CssClass="table table-hover text-center" DataKeyNames="ID" runat="server" >
            <Columns>
                <asp:TemplateField HeaderText="Role Name" HeaderStyle-CssClass="text-center" SortExpression="RoleName">
                    <ItemTemplate>
                        <asp:Label ID="RoleNameTxt" runat="server" Text='<%# Bind("RoleName") %>' />
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="RoleNameTBX" runat="server" CssClass="form-control" Text='<%# Bind("RoleName") %>' />
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Accessible Screens" ControlStyle-BorderStyle="None">
                    <ItemTemplate>
                        <asp:CheckBoxList ID="ScreenAccessCBLPrev" RepeatDirection="Horizontal" DataSourceID="RolesScreensEDS" DataTextField="ScreenName" DataValueField="ID" Enabled="false" runat="server"></asp:CheckBoxList>
                        <asp:EntityDataSource ID="RolesScreensEDS" runat="server" ConnectionString="name=DIMContainerDB_Revised_DevEntities" DefaultContainerName="DIMContainerDB_Revised_DevEntities" EnableFlattening="False" EntitySetName="ScreenMasters" Select="it.[ID], it.[ScreenName]">
                        </asp:EntityDataSource> 
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:CheckBoxList ID="ScreenAccessCBLEdit" RepeatDirection="Horizontal" DataSourceID="RolesScreensEDS1" DataTextField="ScreenName" DataValueField="ID" runat="server"></asp:CheckBoxList>
                        <asp:EntityDataSource ID="RolesScreensEDS1" runat="server" ConnectionString="name=DIMContainerDB_Revised_DevEntities" DefaultContainerName="DIMContainerDB_Revised_DevEntities" EnableFlattening="False" EntitySetName="ScreenMasters" Select="it.[ID], it.[ScreenName]">
                        </asp:EntityDataSource> 
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:CommandField CausesValidation="false" ShowEditButton="true" ShowDeleteButton="true" DeleteText="Delete" EditText="Edit" />
            </Columns>
        </asp:GridView>
    </div> 
</asp:Content>
